### ISSUE TITLE
Err on setup: concurrent map read and map write

### ISSUE THREAD

**Issue by shojaeix** [temporalio/sdk-go#1145]
I'm initiating a Temporal test server in the tests. 
Before each test, I create a server, and after each test, I close that server. 
So the server is in its and closes a few times. 

## Expected Behavior
Success or a standard error!

## Actual Behavior
Failing due to concurrent read/write from the map

## Log trace 
```

goroutine 723 [running]:
github.com/temporalio/tchannel-go/json.Register.func1({0x339d218, 0xc0007ee030}, 0xc00037e600)
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/json/handler.go:100 +0x4e
github.com/temporalio/tchannel-go.HandlerFunc.Handle(0xc00026d0e0?, {0x339d218?, 0xc0007ee030?}, 0x2143900?)
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:49 +0x2f
github.com/temporalio/tchannel-go.(*handlerMap).Handle(0x444f31?, {0x339d218, 0xc0007ee030}, 0xc00037e600)
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:123 +0x21c
github.com/temporalio/tchannel-go.channelHandler.Handle({0x22b0a80?}, {0x339d218, 0xc0007ee030}, 0xc00037e600)
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/handlers.go:131 +0x5a
github.com/temporalio/tchannel-go.(*Connection).dispatchInbound(0xc00074a580, 0x0?, 0x0?, 0xc00037e600, 0xc000402940?)
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:203 +0x454
created by github.com/temporalio/tchannel-go.(*Connection).handleCallReq
	/home/runner/go/pkg/mod/github.com/temporalio/tchannel-go@v1.22.1-0.20220818200552-1be8d8cffa5b/inbound.go:125 +0xe2a
```
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: `v1.22.1` (check the log trace)
  - Platform:

**Comment by cretz** [comment]
This looks like the same `tchannel-go` concurrent map write issue as https://github.com/temporalio/temporal/issues/4000. This is a server-side issue I am afraid.

**Comment by Quinn-With-Two-Ns** [comment]
Closing as duplicate  of https://github.com/temporalio/temporal/issues/4000
