### ISSUE TITLE
Concurrent map writes with ActivityTestEnvironment

### ISSUE THREAD

**Issue by hodbn** [temporalio/sdk-go#1324]
## Expected Behavior
A test activity environment can execute multiple activities in parallel.

I'm assuming this is the expected behavior since one can execute multiple parallel activities on a real workflow.
Also, the [docs](https://docs.temporal.io/dev-guide/go/testing#test-activities) doesn't specify this limit.

## Actual Behavior
A test activity environment might crash (race) when executing multiple activities in parallel.
The cause looks to be [concurrent reads and writes](https://github.com/temporalio/sdk-go/blob/5d5b9c4c44a3f00df55958147b052d1e27233a4f/internal/internal_workflow_testsuite.go#L1340-L1351) to a map in `testWorkflowEnvironmentImpl`.
```
playground › go test ./...
?       github.com/example/playground/helloworld       [no test files]
?       github.com/example/playground/helloworld/starter       [no test files]
?       github.com/example/playground/helloworld/worker        [no test files]
fatal error: concurrent map read and map write

goroutine 88 [running]:
go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).getActivityHandle(0x1400029a1e0, {0x1400038073e, 0x2}, {0x105777eaf?, 0x10577b469?})
        /Users/user/.go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/internal_workflow_testsuite.go:1286 +0xa8
go.temporal.io/sdk/internal.(*activityExecutorWrapper).Execute(0x1400038d7e0, {0x105aa5ef8?, 0x14000412070}, 0x0)
        /Users/user/.go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/internal_workflow_testsuite.go:1623 +0x118
go.temporal.io/sdk/internal.(*activityTaskHandlerImpl).Execute(0x140003d5420, {0x10577b47f, 0x16}, 0x140003e4210)
        /Users/user/.go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/internal_task_handlers.go:2084 +0x6f4
go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).executeActivity(0x1400029a1e0, {0x105930b60?, 0x105a96a00?}, {0x0, 0x0, 0x0})
        /Users/user/.go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/internal_workflow_testsuite.go:603 +0x49c
go.temporal.io/sdk/internal.(*TestActivityEnvironment).ExecuteActivity(0x140003c09c0?, {0x105930b60?, 0x105a96a00?}, {0x0?, 0x1533bc000000000?, 0x6577fa36?})
        /Users/user/.go/pkg/mod/go.temporal.io/sdk@v1.25.1/internal/workflow_testsuite.go:191 +0x2c
github.com/example/playground_test.TestSomething.func1(0x0?)
        /Users/user/git/playground/main_test.go:23 +0x48
testing.tRunner(0x140003c09c0, 0x1400038c850)
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 19
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/testing/testing.go:1648 +0x33c

```

## Steps to Reproduce the Problem

  1. Run this with `go test ./...`:
```golang
// main_test.go
package main_test

import (
	"context"
	"fmt"
	"testing"

	"go.temporal.io/sdk/testsuite"
)

func NopActivity(ctx context.Context) error {
	return nil
}

func TestSomething(t *testing.T) {
	testSuite := &testsuite.WorkflowTestSuite{}
	env := testSuite.NewTestActivityEnvironment()
	env.RegisterActivity(NopActivity)

	for i := 0; i < 100; i++ {
		t.Run(fmt.Sprintf("iter-%d", i), func(t *testing.T) {
			t.Parallel()
			_, _ = env.ExecuteActivity(NopActivity)
		})
	}
}
```
  2. Most times you'll get a crash. You can play with the number of iterations.

## Specifications

  - Version: go sdk `v1.25.1`
  - Platform: macOS

**Comment by Quinn-With-Two-Ns** [comment]
The `ActivityTestEnvironment` is not designed to be thread safe. There is no documentation that says it is OK to use in multiple go routines. In the sdk-go package I would assume an API is not thread safe unless explicitly documented.
