### ISSUE TITLE
Test environment `RegisterDelayedCallback()` with 0 duration which performs a query crashes

### ISSUE THREAD

**Issue by vkarpov15** [temporalio/sdk-go#433]
## Expected Behavior

Consider the below test:

```javascript
func (s *UnitTestSuite) Test_AddToCart() {
	cart := CartState{Items: make([]CartItem, 0)}

	s.env.RegisterDelayedCallback(func() {
		// suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
		res, err := s.env.QueryWorkflow("getCart")
		s.NoError(err)
		err = res.Get(&cart)
		s.NoError(err)
		s.Equal(len(cart.Items), 0)

		update := AddToCartSignal{
			Route: RouteTypes.ADD_TO_CART,
			Item: CartItem{ProductId: 1, Quantity: 1},
		}
		s.env.SignalWorkflow("cartMessages", update)
		fmt.Println(cart.Items)
	}, time.Millisecond*0)

	s.env.ExecuteWorkflow(CartWorkflow, cart)

	res, err := s.env.QueryWorkflow("getCart")
	s.NoError(err)
	err = res.Get(&cart)
	s.NoError(err)
	s.Equal(1, len(cart.Items))

	s.True(s.env.IsWorkflowCompleted())
}
```

I expect this test to succeed. Full code is available in this PR: https://github.com/temporalio/temporal-ecommerce/pull/5

## Actual Behavior

I get a runtime error that points to what looks like [this line](https://github.com/temporalio/sdk-go/blob/3b9239055da4692f37fb16351c924217a688a489/internal/internal_workflow_testsuite.go#L2217). Below is the full stack trace:

```
$ go test
2021/05/06 14:36:04 DEBUG Auto fire timer TimerID 0 TimerDuration 87600h0m0s TimeSkipped 87600h0m0s
--- FAIL: TestUnitTestSuite (0.00s)
    --- FAIL: TestUnitTestSuite/Test_AddToCart (0.00s)
        suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 21 [running]:
            runtime/debug.Stack(0xc000213400, 0xedf4a0, 0x16f65b0)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
            github.com/stretchr/testify/suite.failOnPanic(0xc000103380)
            	/home/val/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x57
            panic(0xedf4a0, 0x16f65b0)
            	/usr/local/go/src/runtime/panic.go:969 +0x1b9
            go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).queryWorkflow(0xc000103680, 0x101d289, 0x7, 0x0, 0x0, 0x0, 0xc00049c000, 0xc00049c000, 0x203000, 0x20)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow_testsuite.go:2211 +0x9d
            go.temporal.io/sdk/internal.(*TestWorkflowEnvironment).QueryWorkflow(...)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/workflow_testsuite.go:714
            temporal-ecommerce/app.(*UnitTestSuite).Test_AddToCart.func1()
            	/home/val/Workspace/meanIT/temporal-ecommerce/workflow_test.go:38 +0x78
            go.temporal.io/sdk/internal.(*testCallbackHandle).processCallback(0xc0002137a0)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow_testsuite.go:691 +0x77
            go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).startMainLoop(0xc000103680)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow_testsuite.go:650 +0xd9
            go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).executeWorkflowInternal(0xc000103680, 0x0, 0x168af3f, 0xc, 0xc000471720)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow_testsuite.go:493 +0x21a
            go.temporal.io/sdk/internal.(*testWorkflowEnvironmentImpl).executeWorkflow(0xc000103680, 0xeb9440, 0x106aa50, 0xc0004378d0, 0x1, 0x1)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow_testsuite.go:437 +0x119
            go.temporal.io/sdk/internal.(*TestWorkflowEnvironment).ExecuteWorkflow(...)
            	/home/val/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/workflow_testsuite.go:487
            temporal-ecommerce/app.(*UnitTestSuite).Test_AddToCart(0xc0001290e0)
            	/home/val/Workspace/meanIT/temporal-ecommerce/workflow_test.go:55 +0x20a
            reflect.Value.call(0xc000483620, 0xc0001270e8, 0x13, 0x101a265, 0x4, 0xc00006ce30, 0x1, 0x1, 0xc00006ccf8, 0x40d34a, ...)
            	/usr/local/go/src/reflect/value.go:476 +0x8c7
            reflect.Value.Call(0xc000483620, 0xc0001270e8, 0x13, 0xc00006ce30, 0x1, 0x1, 0x24, 0xc00005ae50, 0x456354)
            	/usr/local/go/src/reflect/value.go:337 +0xb9
            github.com/stretchr/testify/suite.Run.func1(0xc000103380)
            	/home/val/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x379
            testing.tRunner(0xc000103380, 0xc00020ad80)
            	/usr/local/go/src/testing/testing.go:1123 +0xef
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1168 +0x2b3
FAIL
exit status 1
FAIL	temporal-ecommerce/app	0.005s
```

If I remove the `Select()` call from the workflow, I don't get this error. I also don't get this error if I query the workflow outside of `RegisterDelayedCallback()`

## Steps to Reproduce the Problem

  1. Clone https://github.com/temporalio/temporal-ecommerce
  1. `cd temporal-ecommerce`
  1. `go test`

## Specifications

  - Version: 1.6.0
  - Platform: Xubuntu 18.04

**Comment by vitarb** [comment]
Thanks for the report. I'm a little confused, I don't see Select in your code, neither in the sample you've provided in the description nor in your PR. Could you clarify please?

**Comment by vkarpov15** [comment]
Yeah,  the `Select()` call is in [`workflow.go`](https://github.com/temporalio/temporal-ecommerce/blob/75637b7478b27018a8dfa766945b29f1710ee656/workflow.go#L132), the file that's being tested. Below is a simplified version:

```go
func CartWorkflow(ctx workflow.Context, state CartState) error {
	logger := workflow.GetLogger(ctx)

	err := workflow.SetQueryHandler(ctx, "getCart", func(input []byte) (CartState, error) {
		return state, nil
	})
	if err != nil {
		logger.Info("SetQueryHandler failed.", "Error", err)
		return err
	}

	channel := workflow.GetSignalChannel(ctx, SignalChannelName)
	checkedOut := false
	sentAbandonedCartEmail := false

	for {
		selector := workflow.NewSelector(ctx)
		selector.AddReceive(channel, func(c workflow.ReceiveChannel, _ bool) {
			var signal interface{}
			c.Receive(ctx, &signal)

			var routeSignal RouteSignal
			err := mapstructure.Decode(signal, &routeSignal)
			if err != nil {
				logger.Error("Invalid signal type %v", err)
				return
			}

			// Handle routeSignal
		})

		if !sentAbandonedCartEmail && len(state.Items) > 0 {
			selector.AddFuture(workflow.NewTimer(ctx, abandonedCartTimeout), func(f workflow.Future) {
				sentAbandonedCartEmail = true
				ao := workflow.ActivityOptions{
					ScheduleToStartTimeout: time.Minute,
					StartToCloseTimeout:    time.Minute,
				}

				ctx = workflow.WithActivityOptions(ctx, ao)

				err := workflow.ExecuteActivity(ctx, SendAbandonedCartEmail, state.Email).Get(ctx, nil)
				if err != nil {
					logger.Error("Error sending email %v", err)
					return
				}
			})
		}

		selector.Select(ctx) // <-- `Select()` here

		if checkedOut {
			break
		}
	}

	return nil
}
```

**Comment by Sushisource** [comment]
@vkarpov15 Dug into this and it is a bug with the test environment for sure. 0 duration on `RegisterDelayedCallback` will always break if you try to query inside of it because of a bug where the query handler isn't registered yet. I'll fix this. In the meantime, using any nonzero duration unblocks you.

**Comment by Sushisource** [comment]
@vkarpov15 Spoke with Max, we decided to update the docstring - supporting this in the test framework would require significant change and it's not really something you could do in the real world in any case, since there's no `QueryWithStart` sort of functionality (which probably wouldn't be very useful anyway).

**Comment by Sushisource** [comment]
Think we can close this now
