### ISSUE TITLE
`make test` fails

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-go#687]
## Expected Behavior

Exit code 0

## Actual Behavior

Exit code 2, ending with this output:

<details>

```
$ make test
...
=== RUN   Test_MockResetWorkflowExecution
    mock_test.go:116: PASS:     ResetWorkflowExecution(string,string)
--- PASS: Test_MockResetWorkflowExecution (0.00s)
PASS
coverage: 25.6% of statements
ok      go.temporal.io/sdk/mocks        0.365s  coverage: 25.6% of statements
=== RUN   TestAsyncBindingsTestSuite
objc[18411]: Attempt to use unknown class 0x7ff859ace260.
SIGABRT: abort
PC=0x7ff818286dfe m=5 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7ff818286dfe
stack: frame={sp:0x7000060b3e58, fp:0x0} stack=[0x700006035338,0x7000060b4f38)
0x00007000060b3d58:  0x0000000000000002  0x0000000000000002 
0x00007000060b3d68:  0x00000000034ea000  0x00000000034ea400 
0x00007000060b3d78:  0x000000000000000c  0x00007000060b3de0 
0x00007000060b3d88:  0x00007ff8180bc619  0x0000000000000000 
0x00007000060b3d98:  0xf6890000c000100c  0x000000000000ffff 
0x00007000060b3da8:  0x0000000000000030  0x0000000000000000 
0x00007000060b3db8:  0x000000000000002d  0x000000000000002d 
0x00007000060b3dc8:  0x0000000000000000  0x00000000034ea000 
0x00007000060b3dd8:  0x00007ff859ae2000  0x00007000060b3e10 
0x00007000060b3de8:  0x00007ff8180bc546  0x00007ff8180bc50e 
0x00007000060b3df8:  0x000000000000002d  0x0000000000000001 
0x00007000060b3e08:  0x00007ff859ae2000  0x00007000060b3e50 
0x00007000060b3e18:  0x00007ff8180d8ad6  0x000000000000002c 
0x00007000060b3e28:  0x000000000000002d  0x0000600003300000 
0x00007000060b3e38:  0x0000000000000003  0x0000600002c00000 
0x00007000060b3e48:  0x0000000000000000  0x00007000060b3e80 
0x00007000060b3e58: <0x00007ff818288893  0x0000000000000000 
0x00007000060b3e68:  0x00000020060b3ec0  0x0000600002c00000 
0x00007000060b3e78:  0x00007000060b3ec0  0x0000600003300000 
0x00007000060b3e88:  0x0000000000000003  0x0000000000000080 
0x00007000060b3e98:  0x0000000000000001  0x00007000060b3eb0 
0x00007000060b3ea8:  0x00007ff818288843  0x00007000060b3ef0 
0x00007000060b3eb8:  0x00007ff818154bce  0x0000600002c00080 
0x00007000060b3ec8:  0x0000000000000000  0x0000600002c00000 
0x00007000060b3ed8:  0x00007ffffffffff8  0x00007ff859ace260 
0x00007000060b3ee8:  0x0000000080080001  0x00007000060b3fd0 
0x00007000060b3ef8:  0x00007ff818154b5c  0x0000003000000010 
0x00007000060b3f08:  0x00007000060b3fe0  0x00007000060b3f20 
0x00007000060b3f18:  0x0000000000000000  0x0000000000000000 
0x00007000060b3f28:  0x00007ff859ace260  0x00007ff859ace260 
0x00007000060b3f38:  0x0000000000000001  0x00000000ffffffff 
0x00007000060b3f48:  0x0000000000000000  0x0000000000000000 
runtime: unknown pc 0x7ff818286dfe
stack: frame={sp:0x7000060b3e58, fp:0x0} stack=[0x700006035338,0x7000060b4f38)
0x00007000060b3d58:  0x0000000000000002  0x0000000000000002 
0x00007000060b3d68:  0x00000000034ea000  0x00000000034ea400 
0x00007000060b3d78:  0x000000000000000c  0x00007000060b3de0 
0x00007000060b3d88:  0x00007ff8180bc619  0x0000000000000000 
0x00007000060b3d98:  0xf6890000c000100c  0x000000000000ffff 
0x00007000060b3da8:  0x0000000000000030  0x0000000000000000 
0x00007000060b3db8:  0x000000000000002d  0x000000000000002d 
0x00007000060b3dc8:  0x0000000000000000  0x00000000034ea000 
0x00007000060b3dd8:  0x00007ff859ae2000  0x00007000060b3e10 
0x00007000060b3de8:  0x00007ff8180bc546  0x00007ff8180bc50e 
0x00007000060b3df8:  0x000000000000002d  0x0000000000000001 
0x00007000060b3e08:  0x00007ff859ae2000  0x00007000060b3e50 
0x00007000060b3e18:  0x00007ff8180d8ad6  0x000000000000002c 
0x00007000060b3e28:  0x000000000000002d  0x0000600003300000 
0x00007000060b3e38:  0x0000000000000003  0x0000600002c00000 
0x00007000060b3e48:  0x0000000000000000  0x00007000060b3e80 
0x00007000060b3e58: <0x00007ff818288893  0x0000000000000000 
0x00007000060b3e68:  0x00000020060b3ec0  0x0000600002c00000 
0x00007000060b3e78:  0x00007000060b3ec0  0x0000600003300000 
0x00007000060b3e88:  0x0000000000000003  0x0000000000000080 
0x00007000060b3e98:  0x0000000000000001  0x00007000060b3eb0 
0x00007000060b3ea8:  0x00007ff818288843  0x00007000060b3ef0 
0x00007000060b3eb8:  0x00007ff818154bce  0x0000600002c00080 
0x00007000060b3ec8:  0x0000000000000000  0x0000600002c00000 
0x00007000060b3ed8:  0x00007ffffffffff8  0x00007ff859ace260 
0x00007000060b3ee8:  0x0000000080080001  0x00007000060b3fd0 
0x00007000060b3ef8:  0x00007ff818154b5c  0x0000003000000010 
0x00007000060b3f08:  0x00007000060b3fe0  0x00007000060b3f20 
0x00007000060b3f18:  0x0000000000000000  0x0000000000000000 
0x00007000060b3f28:  0x00007ff859ace260  0x00007ff859ace260 
0x00007000060b3f38:  0x0000000000000001  0x00000000ffffffff 
0x00007000060b3f48:  0x0000000000000000  0x0000000000000000 

goroutine 6 [syscall]:
runtime.cgocall(0x1001140, 0xc000087ca0)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:156 +0x6e fp=0xc000087c78 sp=0xc000087c40 pc=0x1044b8e
net._C2func_getaddrinfo(0xc000038186, 0x0, 0xc0000a6120, 0xc000010020)
        _cgo_gotypes.go:97 +0x8b fp=0xc000087ca0 sp=0xc000087c78 pc=0x159ffeb
net.cgoLookupIPCNAME.func1({0xc000038186, 0xa, 0xc0001b2f0f}, 0x10af825, 0x28448e0)
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:163 +0xb2 fp=0xc000087d10 sp=0xc000087ca0 pc=0x15a2cb2
net.cgoLookupIPCNAME({0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0x1})
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:163 +0x26e fp=0xc000087f10 sp=0xc000087d10 pc=0x15a21ae
net.cgoIPLookup(0x28448f0, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0x9})
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:220 +0x67 fp=0xc000087f80 sp=0xc000087f10 pc=0x15a2dc7
net.cgoLookupIP·dwrap·22()
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:230 +0x72 fp=0xc000087fe0 sp=0xc000087f80 pc=0x15a3472
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x10acb01
created by net.cgoLookupIP
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:230 +0x1ba

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000254b60, {0x1fb648b, 0x1a}, 0x1ff34f8)
        /usr/local/opt/go/libexec/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
        /usr/local/opt/go/libexec/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc000254b60, 0xc0003dfbc0)
        /usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000294680, {0x282f380, 0x2, 0x2}, {0x0, 0xc000213880, 0x28482a0})
        /usr/local/opt/go/libexec/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000294680)
        /usr/local/opt/go/libexec/src/testing/testing.go:1504 +0x9d2
main.main()
        _testmain.go:95 +0x32c

goroutine 19 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc000530390, {0x2135a20, 0xc0005307e0}, 0x1, {{0x1fb850d, 0x0}, {0x2135a20, 0xc0005307e0}})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/picker_wrapper.go:103 +0x1f6
google.golang.org/grpc.(*ClientConn).getTransport(0xc00040c500, {0x2135a20, 0xc0005307e0}, 0x78, {0x1fb850d, 0x1c})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:955 +0x9b
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc00040a300, 0x0)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:408 +0xf3c
google.golang.org/grpc.newClientStreamWithParams({0x21359e8, 0xc000524840}, 0x2844880, 0xc00040c500, {0x1fb850d, 0x1fb850d}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:298 +0x118b
google.golang.org/grpc.newClientStream.func2({0x21359e8, 0xc000524840}, 0xc000524840)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:184 +0x19a
google.golang.org/grpc.newClientStream({0x21359e8, 0xc000524840}, 0x2844880, 0xc00040c500, {0x1fb850d, 0x2}, {0xc00020ffc0, 0x2, 0x2})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/stream.go:212 +0x714
google.golang.org/grpc.invoke({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x4, {0xc00020ffc0, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/call.go:66 +0xd3
go.temporal.io/sdk/internal/common/metrics.NewGRPCInterceptor.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0xc0004c6680}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x10af825, 0x1ff3640, ...)
        /Users/me/gh/sdk-go/internal/common/metrics/grpc.go:67 +0x315
google.golang.org/grpc.getChainUnaryInvoker.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x3710a68, {0xc00020ffc0, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0x1ac
github.com/grpc-ecosystem/go-grpc-middleware/retry.UnaryClientInterceptor.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x1b3e001, 0xc0005306c0, ...)
        /Users/me/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/retry/retry.go:36 +0x16b
google.golang.org/grpc.getChainUnaryInvoker.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x8, {0xc0004c6640, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0x1ac
go.temporal.io/sdk/internal/common/retry.NewRetryOptionsInterceptor.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x1facb3b, 0xc000530690, ...)
        /Users/me/gh/sdk-go/internal/common/retry/interceptor.go:157 +0xa77
google.golang.org/grpc.getChainUnaryInvoker.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x30, {0xc00020fd80, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0x1ac
go.temporal.io/sdk/internal/common/metrics.NewGRPCInterceptor.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x10}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x0, 0xc000530630, ...)
        /Users/me/gh/sdk-go/internal/common/metrics/grpc.go:67 +0x315
google.golang.org/grpc.getChainUnaryInvoker.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0xc000524850, {0xc00020fd80, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:356 +0x1ac
go.temporal.io/sdk/internal.errorInterceptor({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x203000, 0xc000530600, ...)
        /Users/me/gh/sdk-go/internal/grpc_dialer.go:180 +0xe6
google.golang.org/grpc.chainUnaryClientInterceptors.func1({0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, 0x2848a80, 0x1ff3640, ...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:344 +0x167
google.golang.org/grpc.(*ClientConn).Invoke(0xc00040c500, {0x21359e8, 0xc000524840}, {0x1fb850d, 0x1c}, {0x1ef3c80, 0xc0004c6600}, {0x1ef3d40, 0xc0005305d0}, {0x0, ...})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/call.go:35 +0x26c
google.golang.org/grpc/health/grpc_health_v1.(*healthClient).Check(0xc0004def80, {0x21359e8, 0xc000524840}, 0xda80e388, {0x0, 0x0, 0x0})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/health/grpc_health_v1/health_grpc.pb.go:56 +0xfd
go.temporal.io/sdk/internal.checkHealth.func1()
        /Users/me/gh/sdk-go/internal/client.go:811 +0xec
go.temporal.io/sdk/internal/common/backoff.Retry({0x21359e8, 0xc0005247e0}, 0xc00021b5d0, {0x212b808, 0xc0001a0d20}, 0x0)
        /Users/me/gh/sdk-go/internal/common/backoff/retry.go:107 +0x124
go.temporal.io/sdk/internal.checkHealth({0x212bb00, 0xc00040c500}, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /Users/me/gh/sdk-go/internal/client.go:808 +0x2c5
go.temporal.io/sdk/internal.NewClient({{0x1faac09, 0xe}, {0x1fb6a21, 0x1a}, {0x2136dd0, 0xc0001b0fd8}, {0x2137460, 0x2878678}, {0x0, 0x0}, ...})
        /Users/me/gh/sdk-go/internal/client.go:653 +0x6c5
go.temporal.io/sdk/client.NewClient(...)
        /Users/me/gh/sdk-go/client/client.go:436
go.temporal.io/sdk/test_test.(*AsyncBindingsTestSuite).SetupSuite(0xc000294700)
        /Users/me/gh/sdk-go/test/bindings_test.go:68 +0x405
github.com/stretchr/testify/suite.Run(0xc000254d00, {0x212b880, 0xc000294700})
        /Users/me/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:118 +0x5b8
go.temporal.io/sdk/test_test.TestAsyncBindingsTestSuite(0x0)
        /Users/me/gh/sdk-go/test/bindings_test.go:61 +0x45
testing.tRunner(0xc000254d00, 0x1ff34f8)
        /usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
        /usr/local/opt/go/libexec/src/testing/testing.go:1306 +0x727

goroutine 20 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0005224b0)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/balancer_conn_wrappers.go:77 +0x15c
created by google.golang.org/grpc.newCCBalancerWrapper
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/balancer_conn_wrappers.go:67 +0x4d9

goroutine 21 [select]:
net.(*Resolver).lookupIPAddr(0x28448e0, {0x21359e8, 0xc0000a0120}, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0x9})
        /usr/local/opt/go/libexec/src/net/lookup.go:302 +0x81c
net.(*Resolver).internetAddrList(0x21359e8, {0x21359e8, 0xc0000a0120}, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0xe})
        /usr/local/opt/go/libexec/src/net/ipsock.go:288 +0x7c6
net.(*Resolver).resolveAddrList(0x2878678, {0x21359e8, 0xc0000a0120}, {0x1fa134d, 0x4}, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0xe}, {0x0, ...})
        /usr/local/opt/go/libexec/src/net/dial.go:221 +0x556
net.(*Dialer).DialContext(0xc000216a28, {0x21359e8, 0xc0000a0120}, {0x1fa0d8a, 0x10484ad}, {0xc0001b2f0f, 0x1e528e0})
        /usr/local/opt/go/libexec/src/net/dial.go:406 +0x6e5
google.golang.org/grpc/internal/transport.proxyDial({0x21359e8, 0xc0000a0120}, {0xc0001b2f0f, 0x0}, {0x1faab53, 0xe})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/internal/transport/proxy.go:125 +0x11f
google.golang.org/grpc/internal/transport.dial({0x21359e8, 0xc0000a0120}, 0x0, {{0xc0001b2f0f, 0xe}, {0xc0001b2f0f, 0xe}, 0x0, 0x0, 0x0, ...}, ...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/internal/transport/http2_client.go:171 +0x3bc
google.golang.org/grpc/internal/transport.newHTTP2Client({_, _}, {_, _}, {{0xc0001b2f0f, 0xe}, {0xc0001b2f0f, 0xe}, 0x0, 0x0, ...}, ...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/internal/transport/http2_client.go:204 +0x191
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/internal/transport/transport.go:576
google.golang.org/grpc.(*addrConn).createTransport(_, {{0xc0001b2f0f, 0xe}, {0xc0001b2f0f, 0xe}, 0x0, 0x0, 0x0, {0x0, 0x0}}, ...)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:1312 +0x8ab
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc00055a000, {0xc000522500, 0x1, 0x0}, {0x10be125, 0xc00040c8e8, 0x28482a0})
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:1249 +0x518
google.golang.org/grpc.(*addrConn).resetTransport(0xc00055a000)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:1184 +0x20b
google.golang.org/grpc.(*addrConn).connect(0xc00055a000)
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/clientconn.go:845 +0xbc
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
        /Users/me/go/pkg/mod/google.golang.org/grpc@v1.42.0/balancer_conn_wrappers.go:285 +0x125

goroutine 5 [select]:
net.cgoLookupIP({0x2135978, 0xc00009e140}, {0x1fa0d8a, 0x9}, {0xc0001b2f0f, 0x0})
        /usr/local/opt/go/libexec/src/net/cgo_unix.go:231 +0x289
net.(*Resolver).lookupIP(0x28448e0, {0x2135978, 0xc00009e140}, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0x9})
        /usr/local/opt/go/libexec/src/net/lookup_unix.go:97 +0x113
net.glob..func1({0x2135978, 0xc00009e140}, 0xc000088150, {0x1fa0d8a, 0x3}, {0xc0001b2f0f, 0x9})
        /usr/local/opt/go/libexec/src/net/hook.go:23 +0x89
net.(*Resolver).lookupIPAddr.func1()
        /usr/local/opt/go/libexec/src/net/lookup.go:296 +0x133
internal/singleflight.(*Group).doCall(0x28448f0, 0xc0000320a0, {0xc000038173, 0xd}, 0xc00009e180)
        /usr/local/opt/go/libexec/src/internal/singleflight/singleflight.go:95 +0x68
created by internal/singleflight.(*Group).DoChan
        /usr/local/opt/go/libexec/src/internal/singleflight/singleflight.go:88 +0x59b

rax    0x2000209
rbx    0x80
rcx    0x7000060b3e58
rdx    0x0
rdi    0x8
rsi    0x1
rbp    0x7000060b3ea0
rsp    0x7000060b3e58
r8     0x600002c00000
r9     0x80
r10    0x0
r11    0x246
r12    0x0
r13    0x0
r14    0x1
r15    0x8
rip    0x7ff818286dfe
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
FAIL    go.temporal.io/sdk/test 0.435s
FAIL
make: *** [integration-test-zero-cache] Error 1
```

</details>

`make check` and `make unit-test` succeed, as does:

```
$ cd test && go test -run ^TestAsyncBindingsTestSuite$ .
ok      go.temporal.io/sdk/test 1.726s
```

## Steps to Reproduce the Problem

  1. `make test`

## Specifications

  - Version: master
  - Platform: Mac 12.1

**Comment by cretz** [comment]
I cannot replicate this. From the `Makefile`, `make test` is the equivalent of `make unit-test`, `make integration-test-zero-cache`, and `make integration-test-normal-cache`.

Your error seems to be a mac-specific known issue when using race detector on mac. Can you look at https://github.com/golang/go/issues/49138 and see if anything in that issue helps? It looks like Go 1.18 will fix this per https://github.com/golang/go/commit/5f6552018d1ec920c3ca3d459691528f48363c3c, but in the meantime you can mimic what https://github.com/Shopify/toxiproxy/commit/40f632786e8362cb969cc82f33c3d313a6413e88 did (specifically add `MallocNanoZone=0` before running `go test`).

I'm undecided on whether we should alter the makefile for this bug, but if it's a big enough issue we can.

**Comment by lorensr** [comment]
Thanks, that worked! Here's a patch file for anyone else with this issue:

```
diff --git a/Makefile b/Makefile
index 6b523e6..3845bc0 100644
--- a/Makefile
+++ b/Makefile
@@ -46,13 +46,13 @@ unit-test: $(BUILD)/dummy
 integration-test-zero-cache: $(BUILD)/dummy
 	@mkdir -p $(COVER_ROOT)
 	@for dir in $(INTEG_TEST_DIRS); do \
-		(cd "$$dir" &&WORKFLOW_CACHE_SIZE=0 go test $(TEST_ARG) . -coverprofile=$(INTEG_ZERO_CACHE_COVER_FILE) -coverpkg=./...) || exit 1; \
+		(cd "$$dir" &&WORKFLOW_CACHE_SIZE=0 MallocNanoZone=0 go test $(TEST_ARG) . -coverprofile=$(INTEG_ZERO_CACHE_COVER_FILE) -coverpkg=./...) || exit 1; \
 	done;
 
 integration-test-normal-cache: $(BUILD)/dummy
 	@mkdir -p $(COVER_ROOT)
 	@for dir in $(INTEG_TEST_DIRS); do \
-		(cd "$$dir" && go test $(TEST_ARG) . -coverprofile=$(INTEG_NORMAL_CACHE_COVER_FILE) -coverpkg=./...) || exit 1; \
+		(cd "$$dir" && MallocNanoZone=0  go test $(TEST_ARG) . -coverprofile=$(INTEG_NORMAL_CACHE_COVER_FILE) -coverpkg=./...) || exit 1; \
 	done;
 
 test: unit-test integration-test-zero-cache integration-test-normal-cache
```

`git apply patch`
